import os
import sys
import subprocess
from pathlib import Path

# Add project root to path
db_pkg_dir = Path(__file__).parent.resolve()
project_root = db_pkg_dir.parent.parent.resolve()

def load_env():
    """Reads the root .env file and injects variables into os.environ."""
    env_path = project_root / ".env"
    if not env_path.exists():
        print(f"Error: .env file not found at {env_path}")
        sys.exit(1)
        
    print(f"Loading environment from: {env_path}")
    with open(env_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, val = line.split("=", 1)
            # Remove optional quotes from val
            val = val.strip().strip('"').strip("'")
            os.environ[key.strip()] = val

def run_alembic_cmd(args):
    """Executes alembic command with loaded environment variables."""
    # Ensure DATABASE_URL is present
    if not os.getenv("DATABASE_URL"):
        print("Error: DATABASE_URL environment variable is missing.")
        sys.exit(1)
        
    cmd = [sys.executable, "-m", "alembic"] + args
    print(f"Executing: {' '.join(cmd)}")
    
    # Run process from packages/database directory where alembic.ini is
    result = subprocess.run(
        cmd,
        cwd=str(db_pkg_dir),
        env=os.environ.copy()
    )
    if result.returncode != 0:
        print(f"Error: Alembic command failed with code {result.returncode}")
        sys.exit(result.returncode)
    print("Alembic command executed successfully.")

if __name__ == "__main__":
    load_env()
    
    # Default to generating and running the initial migration
    if len(sys.argv) > 1:
        # Pass manual arguments to alembic
        run_alembic_cmd(sys.argv[1:])
    else:
        # Run standard setup sequence
        print("\n--- 1. Generating Initial Autogenerated Revision ---")
        run_alembic_cmd(["revision", "--autogenerate", "-m", "Initial schema migration"])
        
        print("\n--- 2. Deploying Migration Schema to Supabase DB ---")
        run_alembic_cmd(["upgrade", "head"])
