"""Add user_id to AssessmentFile

Revision ID: 0a29c7e5edae
Revises: 3f92085039ed
Create Date: 2026-07-18 18:17:15.173543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Import SQLModel support


# revision identifiers, used by Alembic.
revision: str = '0a29c7e5edae'
down_revision: Union[str, None] = '3f92085039ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_files', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.execute(
        "UPDATE assessment_files "
        "SET user_id = SPLIT_PART(storage_path, '/', 2)::uuid "
        "WHERE user_id IS NULL;"
    )
    op.alter_column('assessment_files', 'user_id', nullable=False)
    op.create_index(op.f('ix_assessment_files_user_id'), 'assessment_files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_files_user_id'), table_name='assessment_files')
    op.drop_column('assessment_files', 'user_id')
    # ### end Alembic commands ###
