"""Initial schema migration

Revision ID: 658ba24a208f
Revises: None
Create Date: 2026-07-17 19:12:43.334731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Import SQLModel support


# revision identifiers, used by Alembic.
revision: str = '658ba24a208f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version_doi_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submitting_pi_custodian', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_assessment', sa.Date(), nullable=False),
    sa.Column('assessor_name_affiliation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cqi_lite_score', sa.Float(), nullable=True),
    sa.Column('cqi_lite_grade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prs_lite_score', sa.Float(), nullable=True),
    sa.Column('prs_lite_risk_band', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('release_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dataset_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_dataset_title'), 'assessments', ['dataset_title'], unique=False)
    op.create_table('assessment_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('factual_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_answers_assessment_id'), 'assessment_answers', ['assessment_id'], unique=False)
    op.create_table('assessment_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_files_assessment_id'), 'assessment_files', ['assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_files_assessment_id'), table_name='assessment_files')
    op.drop_table('assessment_files')
    op.drop_index(op.f('ix_assessment_answers_assessment_id'), table_name='assessment_answers')
    op.drop_table('assessment_answers')
    op.drop_index(op.f('ix_assessments_dataset_title'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
